"""empty message

Revision ID: 31a8e8f6a987
Revises: 
Create Date: 2023-04-05 03:00:42.432976

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import app


# revision identifiers, used by Alembic.
revision = '31a8e8f6a987'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paper',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('corpusId', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('_fieldsOfStudy', sa.String(), nullable=True),
    sa.Column('primaryPaperLink', app.types.paper_link.JSON(), nullable=True),
    sa.Column('alternatePaperLinks', app.types.paper_link.JSON(), nullable=True),
    sa.Column('citationStats', app.types.citation_stats.JSON(), nullable=True),
    sa.Column('publishedAt', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', 'corpusId'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('user',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('username', sa.String(length=120), nullable=True),
    sa.Column('password', sa.String(length=128), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_password'), ['password'], unique=True)

    op.create_table('author',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('fullName', app.types.fullname.JSON(), nullable=True),
    sa.Column('isPublic', sa.BOOLEAN(), nullable=True),
    sa.Column('associationDate', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('userId', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.ForeignKeyConstraint(['userId'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('author', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_author_slug'), ['slug'], unique=True)

    op.create_table('paper_author',
    sa.Column('authorId', sa.String(), nullable=False),
    sa.Column('paperId', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['authorId'], ['author.id'], ),
    sa.ForeignKeyConstraint(['paperId'], ['paper.id'], ),
    sa.PrimaryKeyConstraint('authorId', 'paperId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('paper_author')
    with op.batch_alter_table('author', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_author_slug'))

    op.drop_table('author')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_password'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    op.drop_table('paper')
    # ### end Alembic commands ###
